name: Release artifacts

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  TEMP_DIR: target/github-temp

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: bose-dfu-${{ github.ref_name }}-linux-x86_64
    steps:
      - uses: actions/checkout@v2
      - name: Install libudev headers (for hidapi crate)
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev
      - name: Build
        run: cargo build --verbose --release
      - name: Create temp dir
        run: |
          mkdir -p "$TEMP_DIR"
      - name: Rename binary
        run: |
          mv target/release/bose-dfu "$TEMP_DIR/$ARTIFACT_NAME"
      - name: Add artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.TEMP_DIR }}/${{ env.ARTIFACT_NAME }}

  build-windows:
    runs-on: windows-latest
    env:
      ARTIFACT_NAME: bose-dfu-${{ github.ref_name }}-win-x86_64.exe
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --release
      - name: Create temp dir
        run: |
          mkdir -Force "$Env:TEMP_DIR"
      - name: Rename binary
        run: |
          mv target/release/bose-dfu.exe "${Env:TEMP_DIR}/${Env:ARTIFACT_NAME}"
      - name: Add artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.TEMP_DIR }}/${{ env.ARTIFACT_NAME }}

  build-macos:
    runs-on: macos-latest
    env:
      ARTIFACT_NAME: bose-dfu-${{ github.ref_name }}-mac-universal
    steps:
      - uses: actions/checkout@v2
      - name: Add x86_64-apple-darwin target
        run: rustup target add x86_64-apple-darwin
      - name: Add aarch64-apple-darwin target
        run: rustup target add aarch64-apple-darwin
      - name: Build x86_64
        run: cargo build --verbose --target x86_64-apple-darwin --release
      - name: Build aarch64
        run: cargo build --verbose --target aarch64-apple-darwin --release
      - name: Create temp dir
        run: |
          mkdir -p "$TEMP_DIR"
      - name: Make Universal binary
        run: |
          lipo \
            target/x86_64-apple-darwin/release/bose-dfu \
            target/aarch64-apple-darwin/release/bose-dfu \
            -output "$TEMP_DIR/$ARTIFACT_NAME" -create
      - name: Add artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.TEMP_DIR }}/${{ env.ARTIFACT_NAME }}
